# Generated by Django 5.0.7 on 2025-08-22 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='process',
            new_name='monitor_pro_snapsho_a44cfd_idx',
            old_name='monitor_pro_snapshot_c7a0f8_idx',
        ),
        migrations.RenameIndex(
            model_name='process',
            new_name='monitor_pro_snapsho_b954ff_idx',
            old_name='monitor_pro_snapshot_5e6f0f_idx',
        ),
        migrations.RenameIndex(
            model_name='snapshot',
            new_name='monitor_sna_machine_a0afc8_idx',
            old_name='monitor_sna_machine_c2b2b6_idx',
        ),
    ]
